/**
 * Created by Luke on 01/05/15.
 */

const endpoints = {

  /**
   * source: https://wiki.appnexus.com/display/api/API+Services
   */

  ACCOUNT_RECOVERY_SERVICE: '/account-recovery',
  AD_PROFILE_SERVICE: '/ad-profile',
  AD_QUALITY_RULE_SERVICE: '/ad-quality-rule',
  AD_SERVER_SERVICE: '/ad-server',
  ADVERTISER_SERVICE: '/advertiser',
  APP_INSTALLATION_SERVICE: '/app-installation',
  AUTHENTICATION_SERVICE: '/auth',
  BATCH_SEGMENT_SERVICE: '/batch-segment',
  BRAND_COMPANY_SERVICE: '/brand-company',
  BRAND_SERVICE: '/brand',
  BROKER_SERVICE: '/broker',
  BROWSER_SERVICE: '/browser',
  CAMPAIGN_SERVICE: '/campaign',
  CARRIER_SERVICE: '/carrier',
  CATEGORY_SERVICE: '/category',
  CITY_SERVICE: '/city',
  CLICK_TRACKER_SERVICE: '/clicktracker',
  CONTENT_CATEGORY_SERVICE: '/content-category',
  COUNTRY_SERVICE: '/country',
  CREATIVE_CUSTOM_REQUEST_TEMPLATE_SERVICE: '/creative-custom-request-template',
  CREATIVE_CUSTOM_REQUEST_TEMPLATE_TYPE_SERVICE: '/creative-custom-request-template-type',
  CREATIVE_FOLDER_SERVICE: '/creative-folder',
  CREATIVE_FORMAT_SERVICE: '/creative-format',
  CREATIVE_MACRO_CHECK_SERVICE: '/creative-macro-check',
  CREATIVE_SEARCH_SERVICE: '/creative-search',
  CREATIVE_SERVICE: '/creative',
  CREATIVE_TEMPLATE_SERVICE: '/template',
  CURRENCY_SERVICE: '/currency',
  DEAL_BUYER_ACCESS_SERVICE: '/package-buyer-access',
  DEAL_FROM_PACKAGE_SERVICE: '/deal-from-package',
  DEAL_SERVICE: '/deal',
  DEMOGRAPHIC_AREA_SERVICE: '/dma',
  DEVELOPER_SERVICE: '/developer',
  DEVICE_MAKE_SERVICE: '/device-make',
  DEVICE_MODEL_SERVICE: '/device-model',
  DOMAIN_AUDIT_STATUS_SERVICE: '/url-audit-search',
  DOMAIN_LIST_SERVICE: '/domain-list',
  EXTERNAL_INVENTORY_CODE_SERVICE: '/external-inv-code',
  EXTRACT_CLICKTAGS_SERVICE: '/extract-click-tags',
  FEED_STATUS_SERVICE: '/feed-status',
  IMPRESSION_TRACKER_SERVICE: '/imptracker',
  INSERTION_ORDER_SERVICE: '/insertion-order',
  INVENTORY_ATTRIBUTE_SERVICE: '/inventory-attribute',
  INVENTORY_GROUP_SERVICE: '/inventory-group',
  INVENTORY_RESOLD_SERVICE: '/inventory-resold',
  INVENTORY_SOURCE_SERVICE: '/inventory-source',
  IP_RANGE_LIST_SERVICE: '/ip-range-list',
  LABEL_SERVICE: '/label',
  LANGUAGE_SERVICE: '/language',
  LINE_ITEM_SERVICE: '/line-item',
  LOG_LEVEL_DATA_SERVICE: '/siphon',
  LOOKUP_SERVICE: '/lookup',
  MANUAL_OFFER_RANKING_SERVICE: '/manual-offer-ranking',
  MEDIA_SUBTYPE_SERVICE: '/media-subtype',
  MEDIA_TYPE_SERVICE: '/media-type',
  MEMBER_PROFILE_SERVICE: '/member-profile',
  MEMBER_SERVICE: '/member',
  MOBILE_APP_INSTANCE_LIST_SERVICE: '/mobile-app-instance-list',
  MOBILE_APP_INSTANCE_SERVICE: '/mobile-app-instance',
  MOBILE_APP_SERVICE: '/mobile-app',
  MOBILE_APP_STORE_SERVICE: '/mobile-app-store',
  OBJECT_LIMIT_SERVICE: '/object-limit',
  OPERATING_SYSTEM_EXTENDED_SERVICE: '/operating-system-extended',
  OPERATING_SYSTEM_FAMILY_SERVICE: '/operating-system-family',
  OPERATING_SYSTEM_SERVICE: '/operating-system',
  OPTIMIZATION_ZONE_SERVICE: '/optimization-zone',
  PACKAGE_BUYER_ACCESS_SERVICE: '/package-buyer-access',
  PACKAGE_SERVICE: '/package',
  PAYMENT_RULE_SERVICE: '/payment-rule',
  PIXEL_SERVICE: '/pixel',
  PIXEL_TEMPLATE_SERVICE: '/pixel-template',
  PLACEMENT_SERVICE: '/placement',
  PLATFORM_MEMBER_SERVICE: '/platform-member',
  PLUGIN_INSTANCE_SERVICE: '/plugin-instance',
  PLUGIN_SERVICE: '/plugin',
  PROFILE_SERVICE: '/profile',
  PROFILE_SUMMARY_SERVICE: '/profile-summary',
  PUBLISHER_SERVICE: '/publisher',
  REGION_SERVICE: '/region',
  REPORT_SERVICE: '/report',
  REPORT_STATUS_SERVICE: '/report-status',
  SAVED_REPORT_SERVICE: '/saved-report',
  SEARCH_SERVICE: '/search',
  SEGMENT_SERVICE: '/segment',
  SIPHON_CONFIG_SERVICE: '/siphon-config',
  SITE_SERVICE: '/site',
  TAG_PARSER_SERVICE: '/tag-parser-job',
  TECHNICAL_ATTRIBUTE_SERVICE: '/technical-attribute',
  THIRD_PARTY_PAGE_ACCESS_SERVICE: '/thirdparty-pageaccess',
  THIRD_PARTY_PIXEL_SERVICE: '/thirdparty-pixel',
  TOWN_SERVICE: '/town',
  USER_GROUP_PATTERN_SERVICE: '/usergroup-pattern',
  USER_SERVICE: '/user',
  USER_VERIFICATION_SERVICE: '/user-verification',
  VISIBILITY_PROFILE_SERVICE: '/visibility-profile'

};

export default endpoints;
